# Generated by Django 4.2.6 on 2023-12-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_event_pokemon_pc_event_pokemon_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rounds',
            field=models.IntegerField(default=0),
        ),
    ]
