version: '3.8'
services:
  web:
    build: ./mysite
    image: dmitryshusharin/otrpo:latest
    container_name: otrpo-mysite
    command: sh -c "python manage.py migrate && gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - db-conn
      - redis-conn
  db:
    image: postgres:latest
    container_name: otrpo-db
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-conn
  redis:
    image: redis:7.0.9-alpine
    container_name: otrpo-redis
    restart: unless-stopped
    command: redis-server --port "${REDIS_PORT}"
    volumes:
      - redis-data:/data
    networks:
      - redis-conn
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - db-conn
    ports:
      - "3000:3000"
    volumes:
      - graphana-data:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"

volumes:
  db-data:
  redis-data:
  graphana-data:

networks:
  db-conn:
    driver: bridge
  redis-conn:
    driver: bridge